services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  etl:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./data:/app/data

volumes:
  pgdata:
